### PR TITLE
Add support for optional authentication tokens

### PR DESCRIPTION
**Pull request by rumdood**
Added support for optional auth token for GQL schema request. This should allow for users to utilize sites like GitHub.

### CODE REVIEW

**Comment by mahald** [comment]
Manually add this code as I required it too (my graphql is protected by a jwt).
And all works fine. Please merge.

**Comment by rumdood** [comment]
Did a quick catchup back to the upstream.

**Comment by rumdood** [comment]
Did another catch-up to master

**Comment by Husqvik** [comment]
`--authorization` parameter supported now

**Comment by bartecargo** [comment]
@Husqvik is this still supported? I can't see `--authorization` when I view the help:

```powershell
PS > graphql-client-generator | sls authorization
Either "serviceUrl" or "schemaFileName" parameter must be specified.

PS > graphql-client-generator --version
0.9.10
```

**Comment by nzbart** [comment]
@Husqvik is this still supported? I can't see `--authorization` when I view the help:

```powershell
PS > graphql-client-generator | sls authorization
Either "serviceUrl" or "schemaFileName" parameter must be specified.

PS > graphql-client-generator --version
0.9.10
```

**Comment by Husqvik** [comment]
Correct headers are  more flexible way `--header Authorization:<value>` for some APIs it's required to specify other headers.

**Comment by nzbart** [comment]
Thanks, @Husqvik.

For future reference and anyone else who is interested, this is how I accessed the GitHub graphql API:

```powershell
graphql-client-generator -u https://api.github.com/graphql --header 'Authorization: Bearer <token>'
```

In my case, I used a token with full repo scope, but it may be possible to cut down those permissions. To save some time, this is the page for generating PATs:
* [GitHub Personal access tokens](https://github.com/settings/tokens)

**Pull request closed without merging**
