### PR TITLE
Add support for interface union enum types

### PR DESCRIPTION
**Pull request by tobisor**
Add support for interface union enum graphtypes when generating classes

### CODE REVIEW

**Comment by Husqvik** [comment]
thanks, I incorporated your changes. Also added .NET interface generation so the data classes map GraphQL interfaces 1:1.

**Comment by tobisor** [comment]
hello,
thanks for the incorporation.
i'm still having issues with `GenerateTypeQueryBuilder()` method- since the output is a list of `FileMetadata` objects,  but if it generates an empty list i get:
```
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
            };
```
which produce a compiling error. 

a more generic solution will be outputting 
```
        private static readonly FieldMetadata[] AllFieldMetadata =
            new FieldMetadata[]
            {
            };
```
this fix was part of the commit, and i will be grateful if you incorporate this as well.

**Comment by Husqvik** [comment]
Hm, I didn't expect there can be a GraphQl type without any field. Is that specific for GraphQl unions? Does it make sense to generate the class and builder at all when there is no data field to query?

**Comment by tobisor** [comment]
i think it make sense to generate the code as generic as possible since there are not many options for the generation op (especially when using as a command line).

**Comment by tobisor** [comment]
it is probably specific for union types.
but i think that the question is different, since users of this app are sometimes are clients of the schema they do not know exactly how it's built. so in my opinion the generated code should be generic as much as possible to not make any compilation errors. 

this holds especially for those who uses the command line version which doesn't have any configuration options for the generated code.

**Comment by Husqvik** [comment]
The command line stuff I wrote just as example of use at the very beginning, I believe it's much better to make a build task where you have full control over the generation. Can you share the schema you try to generate? I agree with what you wrote above but but only in case if it's valid case. Generating useless class and builder that even cannot be used it's just a bug.

**Comment by tobisor** [comment]
```
using GraphQL.Types;

namespace Api.Graphql.Schema.Models
{
    public class SenderUnionType : UnionGraphType
    {
        public SenderUnionType ()
        {
            Name = "Sender";
            Type<MaleGraphType>();
            Type<FemaleGraphType>();
        }
    }
}
```
here is one union for example, including no fields but still holds some important information  in case your mailing app is gender-sensitive. 
the generated code will be :
```
    public class SenderQueryBuilder : GraphQlQueryBuilder<SenderQueryBuilder>
    {
        private static readonly FieldMetadata[] AllFieldMetadata =
            new []
            {
            };
    
        protected override IList<FieldMetadata> AllFields { get { return AllFieldMetadata; } } 
    
    }
```
which yields compiling error

**Comment by Husqvik** [comment]
I meant the schema JSON returned by introspection query:

```query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
        }
      }
    }
  }
```

**Comment by tobisor** [comment]
it's a bit of a problem for that moment to send the schema but i can look for specific things if you have any questions.

and yet, regardless the schema, unions are necessary for the queries therefore in my opinion the answer to your question 

>  Does it make sense to generate the class and builder at all when there is no data field to query?

is yes.

**Comment by Logic-Bits** [comment]
Hi,

adding FieldMetadata to [] would at least make it compilable for now.

**Pull request closed without merging**
