### PR TITLE
Support for NonNull GraphQL types RegexScalarFieldTypeMappingProvider

### PR DESCRIPTION
**Pull request by VusalDev**
Proposal to add nullability support to `RegexScalarFieldTypeMappingProvider`.

Let's see an example:
```
  {
    "patternBaseType": ".+",
    "patternValueType": "Long!",
    "patternValueName": ".+",
    "netTypeName": "long"
  },
  {
    "patternBaseType": ".+",
    "patternValueType": "Long",
    "patternValueName": ".+",
    "netTypeName": "long?"
  },
```

Currently, when processing a rule, a GraphQL NonNull type is converted to Nullable type(`Long! -> Long`), 
`valueType = (valueType as GraphQlFieldType)?.UnwrapIfNonNull() ?? valueType;`
so the first rule is always skipped, and the second is executed, generating a .NET type `long?` instead of `long`.

This PR will allow more flexible control over type generation and maintain backward compatibility.

### CODE REVIEW

**Comment by Husqvik** [comment]
This solution doesn't fully fit as there are options and/or use cases affecting nullability. I'll try to revisit this issue in more holistic approach.

**Comment by VusalDev** [comment]
Okay, that would be great. 
Any ideas, how I can separately generate nullable/not nullable structs in current stable version?

**Comment by Husqvik** [comment]
Which way do you use to generate the client. And nullability-wise, do we talk only about the data classes or other (input object class and query builders too)? If you generate using code you can pretty much do whatever you want by implementing your version `IScalarFieldTypeMappingProvider`. You should be able to access everything to resolve nullability of a member.

**Comment by VusalDev** [comment]
I use `dotnet tool graphql-client-generator`. I can fork and maintain version with custom MappingProvider, but I believe it's better to improve original tool.
I expect notnull support only in data classes.

**Comment by danielcweber** [comment]
@Husqvik The issue with `IScalarFieldTypeMappingProvider` we're currently facing is that while we're able to take `NonNull` into account (and strip the .NET type of a trailing '?'), there's no way to determine when the mapping is for a query parameter and when it's for a data class. What then happens is, whenever a schema says that a scalar object field is non-nullable, we would still like to have it nullable on the data class (because we might not retrieve it after all). Setting `DataClassMemberNullability.AlwaysNullable` doesn't help because `GetCustomScalarFieldType` won't get this information.

**Comment by Husqvik** [comment]
@danielcweber @VusalDev reworked the custom scalar type customization support. Haven't changed the actual implementation of `RegexScalarFieldTypeMappingProvider` and the whole thing is still WIP but you can glimpse the changes at https://github.com/Husqvik/GraphQlClientGenerator/commit/eedfdda168d1a545507e2c17bcc7dfd04ec14980

**Pull request closed without merging**
